#!/bin/bash

SENSOR_TEMPERATURE_PATH=$1

TEMPERATURE=$(cat $SENSOR_TEMPERATURE_PATH)
TEMPERATURE_LENGTH=${#TEMPERATURE}
TEMPERATURE=${TEMPERATURE:0:${TEMPERATURE_LENGHT}-3}.${TEMPERATURE:(-3)}
echo ${TEMPERATURE}
